spring:
  application:
    name: magic-vente-stock

  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:5432}/${DATASOURCE_PORT:dil_magic_vente_stock}
    username: ${USERNAME:dil}
    password: ${PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

server:
  port: 8000
  servlet:
    context-path: /magic-vente-stock


# Logs Configuration
logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO


