spring:
  application:
    name: magic-vente-stock

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/dil_magic_vente_stock
    username: postgres
    password: azerty
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

server:
  port: 8000
  servlet:
    context-path: /magic-vente-stock


# Logs Configuration
logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO


